runtime: python39  # Specify the Python runtime version
entrypoint: gunicorn -b :$PORT app:app  # Use Gunicorn as the WSGI server, assuming 'app' is the Flask app in app.py

env: standard  # Using the standard environment
instance_class: F1  # Choosing the smallest available instance class for cost efficiency

automatic_scaling:
  target_cpu_utilization: 0.80
  min_instances: 2
  max_instances: 6
# git commit
handlers:
  - url: /static
    static_dir: static/
    secure: always
    # Cache static files for 30 days; adjust as necessary
    http_headers:
      Cache-Control: "public, max-age=2592000"

  - url: /static/uploads
    static_dir: static/uploads/
    secure: always
    # Cache uploads less aggressively
    http_headers:
      Cache-Control: "public, max-age=3600"


  # All URLs are managed by the Python application
  - url: /.*
    script: auto